<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Resonance</AssemblyName>
    <RootNamespace>Resonance</RootNamespace>
  </PropertyGroup>

  <ItemGroup Condition="'$(NoMinVer)' != 'true'">
    <PackageReference Include="MinVer">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
